//Получаю элементы страницы (инпуты).
export const subReg = document.getElementById('sub_reg')
export const subLog = document.getElementById('sub_login')
export const fname = document.getElementById('fname')
export const username = document.getElementById('username')
export const password = document.getElementById('pass')
export const email = document.getElementById('email')
export const regAlert = document.querySelector('.reg__alert')
export const logAlert = document.querySelector('.log__alert')
export const regForm = document.querySelector('.reg')
export const loginForm = document.querySelector('.login')
export const btnToIn = document.querySelector('.btn--login')
export const btnToUp = document.querySelector('.btn--reg')
export const usernameLogin = document.getElementById('username_login')
export const passwordLogin = document.getElementById('pass_login')
export const btnAdd = document.getElementById('input__add')
export const inputText = document.getElementById('input__text')